stages:
  - build
  - test
  - deploy

build-project:
  stage: build
  script:
    - cd podcast-project
    - npm install
    - npm run build
  image: node:22-alpine
  artifacts:
    paths:
      - podcast-project/dist/

deploy-docker-image:
  stage: deploy
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo Writing docker image to registry $CI_REGISTRY_IMAGE
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/podcast-project/dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:latest"