stages:
  - build
  - deploy

build-frontend:
  stage: build
  script:
    - cd web-frontend
    - npm i
    - npm run build
  image: node:22-alpine
  artifacts:
    paths:
      - web-frontend-v2/dist/

deploy-frontend-docker-image:
  stage: deploy
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo Writing docker image to registry $CI_REGISTRY_IMAGE
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/web-frontend-v2/dockerfile"
      --destination ${CI_REGISTRY_IMAGE}:frontend

deploy-backend-docker-image:
  stage: deploy
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo Writing docker image to registry $CI_REGISTRY_IMAGE
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/server-backend"
      --dockerfile "${CI_PROJECT_DIR}/server-backend/dockerfile"
      --destination ${CI_REGISTRY_IMAGE}:backend