# Apache Docker Image in Version 2.4 laden
FROM httpd:2.4
# Dateien der Seite kopieren
COPY ./web-frontend/dist/ /usr/local/apache2/htdocs/
# Sicherstellen, dass Apache Leserechte für die Dateien hat
RUN chmod -R 755 /usr/local/apache2/htdocs/
# Overwrite Apache configuration with custom config-file
COPY ./web-frontend/custom-httpd.conf /usr/local/apache2/conf/httpd.conf
#Overwrite Apache SSL configuration with custom config-file
COPY ./web-frontend/custom-httpd-ssl.conf /usr/local/apache2/conf/extra/httpd-ssl.conf
